import 'package:flutter/material.dart';
import 'package:flutter_dotenv/flutter_dotenv.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:firebase_core/firebase_core.dart';

import 'app.dart';
import 'core/config/firebase_options.dart';
import 'core/utils/app_logger.dart';

Future<void> main() async {
  // Required before doing anything platform-specific before runApp().
  WidgetsFlutterBinding.ensureInitialized();
  // ignore: avoid_print
  print('DEBUG: WidgetsFlutterBinding done');

  // Load .env — safe to skip in CI/tests where the file may not exist.
  try {
    await dotenv.load(fileName: '.env');
    // ignore: avoid_print
    print('DEBUG: dotenv loaded');
  } catch (e) {
    appLogger.w('No .env file found — using defaults. ($e)');
    // ignore: avoid_print
    print('DEBUG: dotenv failed: $e');
  }

  // Initialize Firebase. `firebase_options.dart` is generated by running
  // `flutterfire configure` locally — see README for the one-time setup.
  // ignore: avoid_print
  print('DEBUG: about to init Firebase');
  // iOS auto-configures Firebase natively from GoogleService-Info.plist
  // before this line ever runs, and that happens outside Dart's view —
  // so `Firebase.apps.isEmpty` can't detect it. Instead, just try to
  // initialize and ignore the "already configured" case specifically.
  try {
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    );
  } catch (e) {
    // ignore: avoid_print
    print('DEBUG: Firebase init threw: ${e.runtimeType} -> $e');
    final message = e.toString();
    if (!message.contains('duplicate-app')) rethrow;
  }
  // ignore: avoid_print
  print('DEBUG: Firebase initialized');

  runApp(
    // ProviderScope makes every Riverpod provider in the widget tree
    // below it available. This should wrap the whole app, exactly once.
    const ProviderScope(
      child: MyApp(),
    ),
  );
  // ignore: avoid_print
  print('DEBUG: runApp called');
}