import 'package:flutter/material.dart';
import 'package:flutter_dotenv/flutter_dotenv.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:firebase_core/firebase_core.dart';

import 'app.dart';
import 'core/config/firebase_options.dart';
import 'core/utils/app_logger.dart';

Future<void> main() async {
  // Required before doing anything platform-specific before runApp().
  WidgetsFlutterBinding.ensureInitialized();

  // Load .env — safe to skip in CI/tests where the file may not exist.
  try {
    await dotenv.load(fileName: '.env');
  } catch (e) {
    appLogger.w('No .env file found — using defaults. ($e)');
  }

  // Initialize Firebase. `firebase_options.dart` is generated by running
  // `flutterfire configure` locally — see README for the one-time setup.
  //
  // iOS auto-configures Firebase natively from GoogleService-Info.plist
  // before this line ever runs, which is invisible to Dart — so on a
  // fresh launch, this call can throw 'duplicate-app' even though
  // nothing is actually wrong. That specific case is safe to ignore.
  try {
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    );
  } catch (e) {
    if (!e.toString().contains('duplicate-app')) rethrow;
  }

  runApp(
    // ProviderScope makes every Riverpod provider in the widget tree
    // below it available. This should wrap the whole app, exactly once.
    const ProviderScope(
      child: MyApp(),
    ),
  );
}
